"""RAD backlash lattice simulator."""

from .cell_geometry import (
    PAPER_RAD_REFERENCE,
    HARDWARE_PROFILE_DIMENSIONS,
    CALIBRATION_MESH_FIELDS,
    CALIBRATION_SOLVER_GAPS,
    CALIBRATION_SOLVER_TASKS,
    CALIBRATION_VISUAL_FIELDS,
    HARDWARE_PROFILE_SCHEMA,
    PaperRADCalibration,
    PaperRADCellGeometry,
    PaperRADCellRecord,
    PaperRADConnectorGeometry,
    PaperRADLatticeGeometry,
    PaperRADReference,
    RADJointGeometry,
    RADCalibrationReadiness,
    RADCalibrationMeasurementTask,
    RADHardwareProfile,
    build_paper_rad_cell_geometry,
    build_paper_rad_lattice_geometry,
    calibrate_paper_rad_config,
    calibration_measurement_plan,
    calibration_readiness,
    config_with_hardware_profile,
    export_hardware_profile_json,
    hardware_profile_from_config,
    hardware_profile_from_dict,
    hardware_profile_from_json,
)
from .cad_mesh_intake import (
    CAD_MESH_AUDIT_SCHEMA,
    MeshBounds,
    cad_mesh_audit,
    export_cad_mesh_audit_json,
    hardware_profile_from_mesh_bounds,
    mesh_bounds_from_file,
)
from .coupling import (
    alpha_to_theta,
    backlash_activation,
    normalized_backlash_to_alpha_dead_zone,
    normalized_backlash_to_theta_dead_zone,
    theta_to_alpha,
)
from .experiments import (
    CalibrationExperimentProtocol,
    CalibrationExperimentSimulation,
    CalibrationExperimentStep,
    CalibrationCellMeasurement,
    CalibrationExperimentComparison,
    CalibrationExperimentMeasurements,
    CalibrationStepMeasurement,
    OperatorInteractionGraph,
    OperatorPairInteraction,
    PairCharacterization,
    PhysicalPairComparison,
    PhysicalResponseComparison,
    ResponseAtlas,
    ResponseAtlasCell,
    ResponseAtlasEntry,
    ResponseAtlasSweep,
    ResponseAtlasSweepSample,
    ResponseCharacterization,
    ResponseDecayProfile,
    ResponseMatrix,
    RemovedTopologyReachabilityComparison,
    SourceCommand,
    TopologyExperimentReport,
    TopologyExperimentScenario,
    TopologyExperimentScenarioResult,
    TopologyComponentResponseSummary,
    build_response_atlas,
    build_response_matrix,
    build_calibration_experiment_protocol,
    build_topology_experiment_report,
    characterize_cluster,
    characterize_pair,
    characterize_pairwise_interactions,
    characterize_response,
    characterize_single_cell,
    compare_physical_cluster,
    compare_physical_pair,
    compare_physical_response,
    compare_removed_topology_reachability,
    calibration_experiment_measurements_from_dict,
    calibration_experiment_measurements_from_json,
    calibration_experiment_protocol_from_dict,
    calibration_experiment_protocol_from_json,
    calibration_experiment_comparison_report,
    calibration_model_profile_from_report,
    calibration_model_profile_holdout_validation,
    calibration_model_profile_residual_comparison,
    calibration_experiment_results_template,
    apply_calibration_model_profile,
    select_calibration_model_profile,
    compare_calibration_experiment_measurements,
    calibration_bench_notebook,
    calibration_bench_packet,
    calibration_bench_execution_validation,
    physical_validation_readiness_report,
    contact_state_abstraction_report,
    contact_graph_consistency_report,
    physical_realization_map_report,
    external_physics_engine_audit_report,
    mujoco_model_export_report,
    mujoco_pin_hole_contact_geometry_report,
    mujoco_contact_parameter_report,
    contact_parameter_calibration_packet,
    contact_parameter_calibration_results_template,
    contact_parameter_calibration_results_from_json,
    compare_contact_parameter_calibration_results,
    contact_parameter_interval_calibration_report,
    mujoco_external_run_report,
    mujoco_external_comparison_report,
    equilibrium_relation_report,
    reachable_equilibrium_controllability_report,
    reachable_equilibrium_bench_protocol,
    reachable_equilibrium_bench_results_template,
    reachable_equilibrium_bench_results_from_json,
    compare_reachable_equilibrium_bench_results,
    reachable_equilibrium_amplitude_calibration_report,
    reachable_equilibrium_empirical_profile_from_amplitude,
    export_calibration_model_profile_json,
    export_calibration_bench_notebook_json,
    export_calibration_bench_notebook_csv,
    export_calibration_bench_packet_json,
    export_calibration_bench_execution_validation_json,
    export_calibration_bench_execution_validation_csv,
    export_physical_validation_readiness_json,
    export_physical_validation_readiness_csv,
    export_contact_state_abstraction_json,
    export_contact_state_abstraction_csv,
    export_contact_graph_consistency_json,
    export_contact_graph_consistency_csv,
    export_physical_realization_map_json,
    export_physical_realization_map_csv,
    export_external_physics_engine_audit_json,
    export_external_physics_engine_audit_csv,
    export_mujoco_model_xml,
    export_mujoco_model_report_json,
    export_mujoco_pin_hole_contact_geometry_json,
    export_mujoco_pin_hole_contact_geometry_csv,
    export_mujoco_contact_parameter_json,
    export_mujoco_contact_parameter_csv,
    export_contact_parameter_calibration_packet_json,
    export_contact_parameter_calibration_packet_csv,
    export_contact_parameter_calibration_results_template_json,
    export_contact_parameter_bench_validation_json,
    export_contact_parameter_bench_validation_csv,
    export_contact_parameter_interval_calibration_json,
    export_contact_parameter_interval_calibration_csv,
    export_mujoco_external_run_json,
    export_mujoco_external_comparison_json,
    export_mujoco_external_comparison_csv,
    export_equilibrium_relation_json,
    export_equilibrium_relation_csv,
    export_reachable_equilibrium_controllability_json,
    export_reachable_equilibrium_controllability_csv,
    export_reachable_equilibrium_bench_protocol_json,
    export_reachable_equilibrium_bench_protocol_csv,
    export_reachable_equilibrium_bench_results_template_json,
    export_reachable_equilibrium_bench_comparison_json,
    export_reachable_equilibrium_bench_comparison_csv,
    export_reachable_equilibrium_amplitude_calibration_json,
    export_reachable_equilibrium_amplitude_calibration_csv,
    export_reachable_equilibrium_empirical_profile_json,
    export_reachable_equilibrium_empirical_profile_csv,
    export_calibration_model_profile_holdout_validation_json,
    export_calibration_model_profile_holdout_validation_csv,
    export_calibration_model_profile_residual_comparison_json,
    export_calibration_model_profile_selection_json,
    export_calibration_experiment_comparison_json,
    export_calibration_experiment_comparison_report_json,
    export_calibration_experiment_protocol_json,
    export_calibration_experiment_results_template_json,
    export_response_atlas_json,
    export_response_atlas_sweep_json,
    export_response_matrix_json,
    export_removed_topology_reachability_comparison_json,
    export_topology_experiment_report_json,
    default_topology_experiment_scenarios,
    run_calibration_experiment_protocol,
    response_decay_profile,
    sweep_response_atlas_parameters,
)
from .framework import (
    ProgrammableDiscontinuityDiagnostic,
    diagnose_programmable_discontinuity,
    export_formalization_target_manifest_json,
    export_programmable_discontinuity_report_json,
    formalization_target_manifest,
    programmable_discontinuity_report,
)
from .kinematic import simulate_kinematic
from .constraint_kinematic import (
    ConstraintKinematicSettings,
    active_neighbor_edges,
    pair_distance_from_theta,
    solve_constraint_kinematic,
)
from .lock_dataset import (
    LockConfigurationRecord,
    LockDataset,
    anchor_coordinates_to_position_locks,
    calibrate_repeated_row_locks_from_lock_dataset,
    calibrate_single_strand_from_lock_dataset,
    export_lock_coordinate_dataset_json,
    export_lock_dataset_summary_json,
    load_lock_dataset,
    lock_coordinate_dataset,
    lock_coordinate_training_arrays,
    lock_angle_vector,
    lock_dataset_summary,
    lock_feature_vector,
    lock_mask,
    lock_record_cell_coordinates,
    parse_lock_filename,
    predict_lock_strand_shape,
    realized_lock_cells,
)
from .lock_neural import (
    export_lock_coordinate_mlp_json,
    predict_lock_coordinate_mlp,
    train_lock_coordinate_mlp,
)
from .inverse import (
    InverseDesignResult,
    InversePhysicalValidation,
    export_inverse_design_report_json,
    export_reachable_equilibrium_profile_inverse_acceptance_csv,
    export_reachable_equilibrium_profile_inverse_acceptance_json,
    export_reachable_equilibrium_profile_inverse_csv,
    export_reachable_equilibrium_profile_inverse_json,
    export_reachable_equilibrium_profile_inverse_preview_packet_csv,
    export_reachable_equilibrium_profile_inverse_preview_packet_json,
    export_reachable_equilibrium_profile_inverse_preview_physical_csv,
    export_reachable_equilibrium_profile_inverse_preview_physical_json,
    export_reachable_equilibrium_profile_inverse_preview_replay_csv,
    export_reachable_equilibrium_profile_inverse_preview_replay_json,
    inverse_design_report,
    reachable_equilibrium_profile_inverse_acceptance_report,
    reachable_equilibrium_profile_inverse_preview_packet,
    reachable_equilibrium_profile_inverse_preview_physical_report,
    reachable_equilibrium_profile_inverse_preview_replay_report,
    reachable_equilibrium_profile_inverse_report,
    solve_inverse_design,
    validate_inverse_design_physical,
)
from .mesh_export import (
    MeshComponent,
    PaperRADMesh,
    build_paper_rad_lattice_mesh,
    export_paper_rad_mesh_obj,
    iter_obj_vertices,
)
from .models import LatticeConfig, LatticeState, LoadCase, SimulationResult
from .two_cell_bench import (
    CAD_RAD_CELL_REFERENCE,
    CAD_RAD_CELL_ARCHIVE_AUDIT_SCHEMA,
    CAD_RAD_CELL_LAYOUT_SCHEMA,
    CAD_RAD_CELL_REFERENCE_PROFILE_SCHEMA,
    ONE_CELL_CAD_EXPORT_AUDIT_SCHEMA,
    TWO_CELL_ACTUATION_SWEEP_SCHEMA,
    TWO_CELL_BENCH_SCHEMA,
    TWO_CELL_CONNECTOR_MEASUREMENT_TEMPLATE_SCHEMA,
    TWO_CELL_CONNECTOR_CONTACT_SCHEMA,
    TWO_CELL_CONNECTOR_CONTACT_SWEEP_SCHEMA,
    TWO_CELL_EXTERNAL_COMPARISON_SCHEMA,
    TWO_CELL_EXTERNAL_FIDELITY_MANIFEST_SCHEMA,
    TWO_CELL_EXTERNAL_FIDELITY_MJCF_RUN_SCHEMA,
    TWO_CELL_EXTERNAL_TEMPLATE_SCHEMA,
    TWO_CELL_FIDELITY_MATRIX_MEASUREMENT_TEMPLATE_SCHEMA,
    TWO_CELL_CONTACT_PHASE_MAP_SCHEMA,
    TWO_CELL_CAD_CONTACT_DECOMPOSITION_SCHEMA,
    TWO_CELL_RADIUS_BACKLASH_PHASE_DIAGRAM_SCHEMA,
    TWO_CELL_RADIUS_BACKLASH_TRANSITION_REPORT_SCHEMA,
    TWO_CELL_MJCF_SCHEMA,
    TWO_CELL_MUJOCO_RUN_SCHEMA,
    TWO_CELL_PACKET_SCHEMA,
    TWO_CELL_PHYSICS_VALIDATION_SCHEMA,
    TWO_CELL_PHYSICAL_FIDELITY_MATRIX_SCHEMA,
    TWO_CELL_PHYSICAL_RESPONSE_ATLAS_SCHEMA,
    TWO_CELL_PHYSICAL_SIMULATION_SUITE_SCHEMA,
    TWO_CELL_QUASISTATIC_SCHEMA,
    TWO_CELL_QUASISTATIC_SWEEP_SCHEMA,
    TWO_CELL_SEGMENTED_CAD_INTAKE_TEMPLATES_SCHEMA,
    TWO_CELL_SEGMENTED_CAD_INTAKE_VALIDATION_SCHEMA,
    TWO_CELL_SEGMENTED_CAD_READINESS_SCHEMA,
    TWO_CELL_EXACT_CONTACT_HANDOFF_PLAN_SCHEMA,
    TWO_CELL_SWEEP_SCHEMA,
    CADRadCellReference,
    TwoCellBenchControls,
    cad_rad_cell_archive_audit,
    cad_rad_cell_layout,
    cad_rad_cell_reference_profile,
    one_cell_cad_export_audit,
    compare_two_cell_external_results,
    export_cad_rad_cell_layout_json,
    export_cad_rad_cell_reference_profile_json,
    export_one_cell_cad_export_audit_json,
    export_cad_rad_cell_archive_audit_json,
    export_two_cell_cad_contact_decomposition_csv,
    export_two_cell_cad_contact_decomposition_json,
    export_two_cell_connector_contact_csv,
    export_two_cell_connector_contact_json,
    export_two_cell_connector_contact_sweep_csv,
    export_two_cell_connector_contact_sweep_json,
    export_two_cell_connector_measurement_template_csv,
    export_two_cell_connector_measurement_template_json,
    export_two_cell_external_comparison_json,
    export_two_cell_external_fidelity_matrix_manifest_csv,
    export_two_cell_external_fidelity_matrix_manifest_json,
    export_two_cell_external_fidelity_mjcf_measurements_csv,
    export_two_cell_external_fidelity_mjcf_run_json,
    export_two_cell_exact_contact_handoff_plan_csv,
    export_two_cell_exact_contact_handoff_plan_json,
    export_two_cell_external_results_template_csv,
    export_two_cell_external_results_template_json,
    export_two_cell_fidelity_matrix_measurement_template_csv,
    export_two_cell_fidelity_matrix_measurement_template_json,
    export_two_cell_contact_phase_map_csv,
    export_two_cell_contact_phase_map_json,
    export_two_cell_radius_backlash_phase_diagram_csv,
    export_two_cell_radius_backlash_phase_diagram_json,
    export_two_cell_radius_backlash_transition_report_csv,
    export_two_cell_radius_backlash_transition_report_json,
    export_two_cell_actuation_sweep_csv,
    export_two_cell_actuation_sweep_json,
    export_two_cell_backlash_sweep_csv,
    export_two_cell_bench_json,
    export_two_cell_measurement_template_csv,
    export_two_cell_mjcf_proxy_json,
    export_two_cell_mjcf_xml,
    export_two_cell_mujoco_proxy_run_json,
    export_two_cell_physical_fidelity_matrix_csv,
    export_two_cell_physical_fidelity_matrix_json,
    export_two_cell_physical_response_atlas_csv,
    export_two_cell_physical_response_atlas_json,
    export_two_cell_physical_test_packet_json,
    export_two_cell_physical_simulation_suite_csv,
    export_two_cell_physical_simulation_suite_json,
    export_two_cell_physics_validation_report_csv,
    export_two_cell_physics_validation_report_json,
    export_two_cell_quasistatic_json,
    export_two_cell_quasistatic_sweep_csv,
    export_two_cell_quasistatic_sweep_json,
    export_two_cell_segmented_cad_intake_templates_csv,
    export_two_cell_segmented_cad_intake_templates_json,
    export_two_cell_segmented_cad_intake_validation_csv,
    export_two_cell_segmented_cad_intake_validation_json,
    export_two_cell_segmented_cad_readiness_csv,
    export_two_cell_segmented_cad_readiness_json,
    simulate_two_cell_bench,
    solve_two_cell_quasistatic,
    sweep_two_cell_backlash,
    sweep_two_cell_quasistatic,
    two_cell_actuation_sweep,
    two_cell_cad_contact_decomposition_spec,
    two_cell_connector_contact_report,
    two_cell_connector_measurement_template,
    two_cell_connector_measurement_template_rows,
    two_cell_external_results_from_csv,
    two_cell_external_results_from_json,
    two_cell_external_results_from_rows,
    two_cell_external_fidelity_matrix_manifest,
    two_cell_external_fidelity_matrix_manifest_rows,
    two_cell_external_fidelity_mjcf_measurement_rows,
    two_cell_external_fidelity_mjcf_measurements_csv,
    two_cell_external_fidelity_mjcf_run_report,
    two_cell_exact_contact_handoff_plan,
    two_cell_external_results_template,
    two_cell_external_results_template_rows,
    two_cell_fidelity_matrix_measurement_template,
    two_cell_fidelity_matrix_measurement_template_rows,
    two_cell_contact_phase_map,
    two_cell_radius_backlash_phase_diagram,
    two_cell_radius_backlash_transition_report,
    two_cell_measurement_template_rows,
    two_cell_mjcf_proxy_report,
    two_cell_mujoco_proxy_run_report,
    two_cell_physical_fidelity_matrix,
    two_cell_physical_response_atlas,
    two_cell_physical_test_packet,
    two_cell_physical_simulation_suite,
    two_cell_physics_validation_report,
    two_cell_segmented_cad_intake_templates,
    two_cell_segmented_cad_intake_validation_report,
    two_cell_segmented_cad_readiness_report,
    sweep_two_cell_connector_contact,
)
from .two_cell_calibration import (
    TWO_CELL_CONNECTOR_MEASUREMENT_COMPARISON_SCHEMA,
    TWO_CELL_FIDELITY_MATRIX_MEASUREMENT_COMPARISON_SCHEMA,
    TWO_CELL_FIDELITY_MATRIX_PARAMETER_CALIBRATION_SCHEMA,
    TWO_CELL_RADIUS_BACKLASH_TRANSITION_COMPARISON_SCHEMA,
    TWO_CELL_RADIUS_BACKLASH_TRANSITION_RERUN_SCHEMA,
    TWO_CELL_EXTERNAL_FIDELITY_BENCHMARK_SCHEMA,
    TWO_CELL_EXTERNAL_FIDELITY_CORRECTION_APPLICATION_SCHEMA,
    TWO_CELL_EXTERNAL_FIDELITY_CORRECTION_SCHEMA,
    TWO_CELL_MEASUREMENT_COMPARISON_SCHEMA,
    TWO_CELL_PARAMETER_CALIBRATION_SCHEMA,
    TwoCellConnectorMeasurement,
    TwoCellMeasurement,
    calibrate_two_cell_parameters,
    calibrate_two_cell_fidelity_matrix_parameters,
    compare_two_cell_connector_measurements,
    compare_two_cell_fidelity_matrix_measurements,
    compare_two_cell_radius_backlash_transition_measurements,
    two_cell_radius_backlash_transition_rerun_report,
    two_cell_external_fidelity_benchmark_summary,
    apply_two_cell_external_fidelity_correction_profile,
    fit_two_cell_external_fidelity_correction_profile,
    compare_two_cell_measurements,
    export_two_cell_connector_measurement_comparison_csv,
    export_two_cell_connector_measurement_comparison_json,
    export_two_cell_fidelity_matrix_measurement_comparison_csv,
    export_two_cell_fidelity_matrix_measurement_comparison_json,
    export_two_cell_fidelity_matrix_parameter_calibration_json,
    export_two_cell_radius_backlash_transition_comparison_csv,
    export_two_cell_radius_backlash_transition_comparison_json,
    export_two_cell_radius_backlash_transition_rerun_csv,
    export_two_cell_radius_backlash_transition_rerun_json,
    export_two_cell_external_fidelity_correction_profile_json,
    export_two_cell_external_fidelity_correction_application_csv,
    export_two_cell_external_fidelity_correction_application_json,
    export_two_cell_measurement_comparison_json,
    export_two_cell_parameter_calibration_json,
    two_cell_connector_measurements_from_csv,
    two_cell_connector_measurements_from_json,
    two_cell_connector_measurements_from_rows,
    two_cell_fidelity_matrix_measurements_from_csv,
    two_cell_fidelity_matrix_measurements_from_json,
    two_cell_fidelity_matrix_measurements_from_rows,
    two_cell_radius_backlash_transition_measurements_from_csv,
    two_cell_radius_backlash_transition_measurements_from_json,
    two_cell_radius_backlash_transition_measurements_from_rows,
    two_cell_measurements_from_csv,
    two_cell_measurements_from_json,
    two_cell_measurements_from_rows,
    write_two_cell_connector_measurement_comparison_artifacts,
    write_two_cell_fidelity_matrix_measurement_comparison_artifacts,
    write_two_cell_radius_backlash_transition_comparison_artifacts,
    write_two_cell_external_fidelity_benchmark_summary_artifact,
    write_two_cell_external_fidelity_correction_profile_artifact,
    write_two_cell_external_fidelity_correction_application_artifacts,
)
from .two_cell_external_fidelity_web import (
    WEB_TWO_CELL_EXTERNAL_FIDELITY_SCHEMA,
    build_two_cell_external_fidelity_web_summary,
    write_two_cell_external_fidelity_web_summary,
)
from .operators import (
    DeadZonePropagationOperator,
    AdjacentSwapDiagnostic,
    EventCommutativityDiagnostic,
    GroupActuationDecompositionDiagnostic,
    GroupRemovalInteractionDiagnostic,
    PropagationResult,
    ProgrammableDiscontinuityEvent,
    SequenceOrderDiagnostic,
    SolverEnergyBreakdown,
    StateDistanceDiagnostic,
    VerticalLoadPhysicalScenario,
    VerticalRemovalPhysicalComparisonDiagnostic,
    VerticalRemovalResidualDiagnostic,
    alpha_backlash_operator,
    apply_event_sequence,
    apply_programmable_event,
    build_vertical_load_physical_preview_report,
    clear_actuation_event,
    compare_event_order,
    compare_group_actuation_decomposition,
    compare_group_actuation_under_removal,
    compare_sequence_order,
    compare_vertical_load_energy_measurement_results,
    compare_vertical_residual_spring_hinge_3d,
    compare_vertical_residual_under_removal,
    default_vertical_load_physical_scenarios,
    evaluate_programmable_operators,
    export_vertical_load_bench_packet_json,
    export_vertical_load_energy_comparison_report_json,
    export_vertical_load_energy_experiment_protocol_json,
    export_vertical_load_energy_measurement_template_json,
    export_vertical_load_energy_validation_json,
    export_vertical_load_physical_preview_report_csv,
    export_vertical_load_physical_preview_report_json,
    export_vertical_removal_physical_comparison_json,
    finite_die_off_radius,
    group_actuation_event,
    lattice_topology_diagnostic,
    local_actuation_event,
    lock_event,
    lock_projection,
    mechanics_energy_certificate_to_dict,
    release_event,
    remove_cell_event,
    restore_cell_event,
    validate_vertical_load_energy_measurements,
    vertical_load_bench_packet,
    vertical_load_energy_experiment_protocol,
    vertical_load_energy_measurement_results_from_json,
    vertical_load_energy_measurement_template,
    vertical_removal_physical_comparison_to_dict,
    vertical_clearance_operator,
)
from .provenance import (
    MODEL_PROVENANCE,
    ModelProvenanceItem,
    model_provenance,
    provenance_by_status,
    provenance_summary,
)
try:
    from .spring_hinge import solve_spring_hinge, solve_spring_hinge_3d
except ModuleNotFoundError as exc:  # pragma: no cover - exercised only in minimal runtimes.
    if exc.name not in {"scipy", "scipy.optimize"}:
        raise
    _SPRING_HINGE_IMPORT_ERROR = exc

    def solve_spring_hinge(*args, **kwargs):
        raise ImportError(
            "SciPy is required for spring-hinge mechanics. Install project dependencies "
            "before using solve_spring_hinge."
        ) from _SPRING_HINGE_IMPORT_ERROR

    def solve_spring_hinge_3d(*args, **kwargs):
        raise ImportError(
            "SciPy is required for spring-hinge mechanics. Install project dependencies "
            "before using solve_spring_hinge_3d."
        ) from _SPRING_HINGE_IMPORT_ERROR
from .unit_scale import (
    export_physical_unit_scale_metadata_json,
    physical_unit_scale_metadata,
)
from .visualization import interactive_app, plot_lattice


def write_vertical_load_bench_packet_artifacts(*args, **kwargs):
    """Write vertical-load bench packet artifacts without preloading the CLI module."""

    from .export_vertical_load_bench_packet import (
        write_vertical_load_bench_packet_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_calibration_bench_packet_artifacts(*args, **kwargs):
    """Write calibration bench packet artifacts without preloading the CLI module."""

    from .export_calibration_bench_packet import (
        write_calibration_bench_packet_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_calibration_bench_execution_validation_artifacts(*args, **kwargs):
    """Write executed calibration validation artifacts without preloading the CLI module."""

    from .compare_calibration_bench_packet import (
        write_calibration_bench_execution_validation_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_browser_lock_dataset_artifact(*args, **kwargs):
    """Write the processed browser lock-coordinate dataset without preloading the CLI module."""

    from .export_lock_dataset_web import (
        write_browser_lock_dataset_artifact as _write_artifact,
    )

    return _write_artifact(*args, **kwargs)


def write_two_cell_bench_packet_artifacts(*args, **kwargs):
    """Write two-cell CAD/contact bench artifacts without preloading the CLI module."""

    from .export_two_cell_bench_packet import (
        write_two_cell_bench_packet_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_two_cell_measurement_comparison_artifacts(*args, **kwargs):
    """Write two-cell measured-vs-model comparison artifacts without preloading the CLI module."""

    from .compare_two_cell_measurements import (
        write_two_cell_measurement_comparison_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_two_cell_external_comparison_artifacts(*args, **kwargs):
    """Write two-cell external-vs-quasistatic comparison artifacts lazily."""

    from .compare_two_cell_external_results import (
        write_two_cell_external_comparison_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


def write_vertical_load_energy_comparison_artifacts(*args, **kwargs):
    """Write filled-measurement comparison artifacts without preloading the CLI module."""

    from .compare_vertical_load_measurements import (
        write_vertical_load_energy_comparison_artifacts as _write_artifacts,
    )

    return _write_artifacts(*args, **kwargs)


__all__ = [
    "LatticeConfig",
    "LatticeState",
    "LoadCase",
    "SimulationResult",
    "LockConfigurationRecord",
    "LockDataset",
    "anchor_coordinates_to_position_locks",
    "PaperRADReference",
    "PaperRADCalibration",
    "RADJointGeometry",
    "PaperRADCellGeometry",
    "PaperRADCellRecord",
    "PaperRADConnectorGeometry",
    "PaperRADLatticeGeometry",
    "MeshComponent",
    "PaperRADMesh",
    "CADRadCellReference",
    "TwoCellBenchControls",
    "TwoCellConnectorMeasurement",
    "TwoCellMeasurement",
    "MeshBounds",
    "PAPER_RAD_REFERENCE",
    "CAD_MESH_AUDIT_SCHEMA",
    "CAD_RAD_CELL_REFERENCE",
    "CAD_RAD_CELL_ARCHIVE_AUDIT_SCHEMA",
    "CAD_RAD_CELL_LAYOUT_SCHEMA",
    "CAD_RAD_CELL_REFERENCE_PROFILE_SCHEMA",
    "ONE_CELL_CAD_EXPORT_AUDIT_SCHEMA",
    "TWO_CELL_ACTUATION_SWEEP_SCHEMA",
    "TWO_CELL_BENCH_SCHEMA",
    "TWO_CELL_CONNECTOR_MEASUREMENT_COMPARISON_SCHEMA",
    "TWO_CELL_CONNECTOR_MEASUREMENT_TEMPLATE_SCHEMA",
    "TWO_CELL_CONNECTOR_CONTACT_SCHEMA",
    "TWO_CELL_CONNECTOR_CONTACT_SWEEP_SCHEMA",
    "TWO_CELL_EXTERNAL_COMPARISON_SCHEMA",
    "TWO_CELL_EXTERNAL_FIDELITY_MANIFEST_SCHEMA",
    "TWO_CELL_EXTERNAL_TEMPLATE_SCHEMA",
    "TWO_CELL_FIDELITY_MATRIX_MEASUREMENT_COMPARISON_SCHEMA",
    "TWO_CELL_FIDELITY_MATRIX_PARAMETER_CALIBRATION_SCHEMA",
    "TWO_CELL_FIDELITY_MATRIX_MEASUREMENT_TEMPLATE_SCHEMA",
    "TWO_CELL_RADIUS_BACKLASH_TRANSITION_COMPARISON_SCHEMA",
    "TWO_CELL_RADIUS_BACKLASH_TRANSITION_RERUN_SCHEMA",
    "TWO_CELL_CONTACT_PHASE_MAP_SCHEMA",
    "TWO_CELL_CAD_CONTACT_DECOMPOSITION_SCHEMA",
    "TWO_CELL_EXACT_CONTACT_HANDOFF_PLAN_SCHEMA",
    "TWO_CELL_RADIUS_BACKLASH_PHASE_DIAGRAM_SCHEMA",
    "TWO_CELL_RADIUS_BACKLASH_TRANSITION_REPORT_SCHEMA",
    "TWO_CELL_MJCF_SCHEMA",
    "TWO_CELL_MUJOCO_RUN_SCHEMA",
    "TWO_CELL_PHYSICS_VALIDATION_SCHEMA",
    "TWO_CELL_PHYSICAL_FIDELITY_MATRIX_SCHEMA",
    "TWO_CELL_PHYSICAL_RESPONSE_ATLAS_SCHEMA",
    "TWO_CELL_PHYSICAL_SIMULATION_SUITE_SCHEMA",
    "TWO_CELL_QUASISTATIC_SCHEMA",
    "TWO_CELL_QUASISTATIC_SWEEP_SCHEMA",
    "TWO_CELL_SEGMENTED_CAD_INTAKE_TEMPLATES_SCHEMA",
    "TWO_CELL_SEGMENTED_CAD_INTAKE_VALIDATION_SCHEMA",
    "TWO_CELL_SEGMENTED_CAD_READINESS_SCHEMA",
    "TWO_CELL_SWEEP_SCHEMA",
    "TWO_CELL_PACKET_SCHEMA",
    "TWO_CELL_MEASUREMENT_COMPARISON_SCHEMA",
    "TWO_CELL_PARAMETER_CALIBRATION_SCHEMA",
    "HARDWARE_PROFILE_DIMENSIONS",
    "HARDWARE_PROFILE_SCHEMA",
    "CALIBRATION_VISUAL_FIELDS",
    "CALIBRATION_MESH_FIELDS",
    "CALIBRATION_SOLVER_GAPS",
    "CALIBRATION_SOLVER_TASKS",
    "PropagationResult",
    "DeadZonePropagationOperator",
    "ProgrammableDiscontinuityEvent",
    "EventCommutativityDiagnostic",
    "GroupActuationDecompositionDiagnostic",
    "GroupRemovalInteractionDiagnostic",
    "VerticalRemovalResidualDiagnostic",
    "VerticalRemovalPhysicalComparisonDiagnostic",
    "VerticalLoadPhysicalScenario",
    "StateDistanceDiagnostic",
    "AdjacentSwapDiagnostic",
    "SequenceOrderDiagnostic",
    "SolverEnergyBreakdown",
    "SourceCommand",
    "OperatorPairInteraction",
    "OperatorInteractionGraph",
    "ResponseCharacterization",
    "ResponseDecayProfile",
    "PairCharacterization",
    "PhysicalResponseComparison",
    "PhysicalPairComparison",
    "RemovedTopologyReachabilityComparison",
    "ResponseAtlasCell",
    "ResponseAtlasEntry",
    "ResponseAtlas",
    "ResponseMatrix",
    "ResponseAtlasSweepSample",
    "ResponseAtlasSweep",
    "TopologyExperimentScenario",
    "TopologyExperimentScenarioResult",
    "TopologyExperimentReport",
    "TopologyComponentResponseSummary",
    "CalibrationExperimentStep",
    "CalibrationExperimentProtocol",
    "CalibrationExperimentSimulation",
    "CalibrationCellMeasurement",
    "CalibrationStepMeasurement",
    "CalibrationExperimentMeasurements",
    "CalibrationExperimentComparison",
    "ProgrammableDiscontinuityDiagnostic",
    "InverseDesignResult",
    "InversePhysicalValidation",
    "ModelProvenanceItem",
    "MODEL_PROVENANCE",
    "RADCalibrationReadiness",
    "RADCalibrationMeasurementTask",
    "RADHardwareProfile",
    "build_paper_rad_cell_geometry",
    "build_paper_rad_lattice_geometry",
    "calibrate_paper_rad_config",
    "calibration_measurement_plan",
    "calibration_readiness",
    "config_with_hardware_profile",
    "hardware_profile_from_config",
    "hardware_profile_from_dict",
    "hardware_profile_from_json",
    "hardware_profile_from_mesh_bounds",
    "export_hardware_profile_json",
    "mesh_bounds_from_file",
    "cad_mesh_audit",
    "export_cad_mesh_audit_json",
    "simulate_two_cell_bench",
    "cad_rad_cell_archive_audit",
    "cad_rad_cell_layout",
    "cad_rad_cell_reference_profile",
    "one_cell_cad_export_audit",
    "two_cell_cad_contact_decomposition_spec",
    "solve_two_cell_quasistatic",
    "sweep_two_cell_backlash",
    "sweep_two_cell_quasistatic",
    "two_cell_actuation_sweep",
    "two_cell_connector_contact_report",
    "two_cell_connector_measurement_template",
    "two_cell_connector_measurement_template_rows",
    "two_cell_connector_measurements_from_rows",
    "two_cell_connector_measurements_from_csv",
    "two_cell_connector_measurements_from_json",
    "two_cell_external_results_from_csv",
    "two_cell_external_results_from_json",
    "two_cell_external_results_from_rows",
    "two_cell_external_fidelity_matrix_manifest",
    "two_cell_external_fidelity_matrix_manifest_rows",
    "two_cell_external_fidelity_mjcf_measurement_rows",
    "two_cell_external_fidelity_mjcf_measurements_csv",
    "two_cell_external_fidelity_mjcf_run_report",
    "two_cell_exact_contact_handoff_plan",
    "two_cell_external_results_template",
    "two_cell_external_results_template_rows",
    "two_cell_fidelity_matrix_measurement_template",
    "two_cell_fidelity_matrix_measurement_template_rows",
    "two_cell_fidelity_matrix_measurements_from_rows",
    "two_cell_fidelity_matrix_measurements_from_csv",
    "two_cell_fidelity_matrix_measurements_from_json",
    "two_cell_radius_backlash_transition_measurements_from_rows",
    "two_cell_radius_backlash_transition_measurements_from_csv",
    "two_cell_radius_backlash_transition_measurements_from_json",
    "two_cell_contact_phase_map",
    "two_cell_radius_backlash_phase_diagram",
    "two_cell_radius_backlash_transition_report",
    "two_cell_radius_backlash_transition_rerun_report",
    "two_cell_external_fidelity_benchmark_summary",
    "apply_two_cell_external_fidelity_correction_profile",
    "fit_two_cell_external_fidelity_correction_profile",
    "two_cell_mjcf_proxy_report",
    "two_cell_mujoco_proxy_run_report",
    "two_cell_physical_fidelity_matrix",
    "two_cell_physical_response_atlas",
    "two_cell_physical_test_packet",
    "two_cell_physical_simulation_suite",
    "two_cell_physics_validation_report",
    "two_cell_segmented_cad_intake_templates",
    "two_cell_segmented_cad_intake_validation_report",
    "two_cell_segmented_cad_readiness_report",
    "sweep_two_cell_connector_contact",
    "export_two_cell_bench_json",
    "export_cad_rad_cell_archive_audit_json",
    "export_cad_rad_cell_layout_json",
    "export_cad_rad_cell_reference_profile_json",
    "export_one_cell_cad_export_audit_json",
    "export_two_cell_actuation_sweep_csv",
    "export_two_cell_actuation_sweep_json",
    "export_two_cell_cad_contact_decomposition_csv",
    "export_two_cell_cad_contact_decomposition_json",
    "export_two_cell_connector_contact_csv",
    "export_two_cell_connector_contact_json",
    "export_two_cell_connector_contact_sweep_csv",
    "export_two_cell_connector_contact_sweep_json",
    "export_two_cell_connector_measurement_comparison_csv",
    "export_two_cell_connector_measurement_comparison_json",
    "export_two_cell_connector_measurement_template_csv",
    "export_two_cell_connector_measurement_template_json",
    "export_two_cell_external_comparison_json",
    "export_two_cell_external_fidelity_matrix_manifest_csv",
    "export_two_cell_external_fidelity_matrix_manifest_json",
    "export_two_cell_external_fidelity_mjcf_measurements_csv",
    "export_two_cell_external_fidelity_mjcf_run_json",
    "export_two_cell_exact_contact_handoff_plan_csv",
    "export_two_cell_exact_contact_handoff_plan_json",
    "export_two_cell_external_results_template_csv",
    "export_two_cell_external_results_template_json",
    "export_two_cell_fidelity_matrix_measurement_comparison_csv",
    "export_two_cell_fidelity_matrix_measurement_comparison_json",
    "export_two_cell_fidelity_matrix_measurement_template_csv",
    "export_two_cell_fidelity_matrix_measurement_template_json",
    "export_two_cell_contact_phase_map_csv",
    "export_two_cell_contact_phase_map_json",
    "export_two_cell_radius_backlash_phase_diagram_csv",
    "export_two_cell_radius_backlash_phase_diagram_json",
    "export_two_cell_radius_backlash_transition_report_csv",
    "export_two_cell_radius_backlash_transition_report_json",
    "export_two_cell_radius_backlash_transition_rerun_csv",
    "export_two_cell_radius_backlash_transition_rerun_json",
    "export_two_cell_mjcf_proxy_json",
    "export_two_cell_mjcf_xml",
    "export_two_cell_mujoco_proxy_run_json",
    "export_two_cell_physical_fidelity_matrix_csv",
    "export_two_cell_physical_fidelity_matrix_json",
    "export_two_cell_physical_response_atlas_csv",
    "export_two_cell_physical_response_atlas_json",
    "export_two_cell_physical_simulation_suite_csv",
    "export_two_cell_physical_simulation_suite_json",
    "export_two_cell_quasistatic_json",
    "export_two_cell_quasistatic_sweep_csv",
    "export_two_cell_quasistatic_sweep_json",
    "export_two_cell_segmented_cad_intake_templates_csv",
    "export_two_cell_segmented_cad_intake_templates_json",
    "export_two_cell_segmented_cad_intake_validation_csv",
    "export_two_cell_segmented_cad_intake_validation_json",
    "export_two_cell_segmented_cad_readiness_csv",
    "export_two_cell_segmented_cad_readiness_json",
    "export_two_cell_physics_validation_report_csv",
    "export_two_cell_physics_validation_report_json",
    "export_two_cell_backlash_sweep_csv",
    "export_two_cell_measurement_template_csv",
    "export_two_cell_physical_test_packet_json",
    "two_cell_measurement_template_rows",
    "two_cell_measurements_from_rows",
    "two_cell_measurements_from_csv",
    "two_cell_measurements_from_json",
    "compare_two_cell_connector_measurements",
    "compare_two_cell_fidelity_matrix_measurements",
    "compare_two_cell_radius_backlash_transition_measurements",
    "compare_two_cell_measurements",
    "calibrate_two_cell_parameters",
    "calibrate_two_cell_fidelity_matrix_parameters",
    "write_two_cell_connector_measurement_comparison_artifacts",
    "write_two_cell_fidelity_matrix_measurement_comparison_artifacts",
    "write_two_cell_radius_backlash_transition_comparison_artifacts",
    "write_two_cell_external_fidelity_benchmark_summary_artifact",
    "write_two_cell_external_fidelity_correction_profile_artifact",
    "write_two_cell_external_fidelity_correction_application_artifacts",
    "WEB_TWO_CELL_EXTERNAL_FIDELITY_SCHEMA",
    "build_two_cell_external_fidelity_web_summary",
    "write_two_cell_external_fidelity_web_summary",
    "export_two_cell_measurement_comparison_json",
    "export_two_cell_fidelity_matrix_parameter_calibration_json",
    "export_two_cell_radius_backlash_transition_comparison_csv",
    "export_two_cell_radius_backlash_transition_comparison_json",
    "export_two_cell_external_fidelity_correction_profile_json",
    "export_two_cell_external_fidelity_correction_application_csv",
    "export_two_cell_external_fidelity_correction_application_json",
    "export_two_cell_parameter_calibration_json",
    "build_paper_rad_lattice_mesh",
    "export_paper_rad_mesh_obj",
    "iter_obj_vertices",
    "build_response_atlas",
    "sweep_response_atlas_parameters",
    "build_response_matrix",
    "compare_removed_topology_reachability",
    "default_topology_experiment_scenarios",
    "build_topology_experiment_report",
    "build_calibration_experiment_protocol",
    "calibration_experiment_results_template",
    "calibration_experiment_measurements_from_dict",
    "calibration_experiment_measurements_from_json",
    "calibration_experiment_protocol_from_dict",
    "calibration_experiment_protocol_from_json",
    "calibration_experiment_comparison_report",
    "calibration_model_profile_from_report",
    "calibration_model_profile_holdout_validation",
    "calibration_model_profile_residual_comparison",
    "apply_calibration_model_profile",
    "select_calibration_model_profile",
    "compare_calibration_experiment_measurements",
    "calibration_bench_notebook",
    "calibration_bench_packet",
    "contact_parameter_calibration_packet",
    "contact_parameter_calibration_results_template",
    "contact_parameter_calibration_results_from_json",
    "compare_contact_parameter_calibration_results",
    "contact_parameter_interval_calibration_report",
    "calibration_bench_execution_validation",
    "physical_validation_readiness_report",
    "contact_state_abstraction_report",
    "contact_graph_consistency_report",
    "physical_realization_map_report",
    "equilibrium_relation_report",
    "reachable_equilibrium_controllability_report",
    "reachable_equilibrium_bench_protocol",
    "reachable_equilibrium_bench_results_template",
    "reachable_equilibrium_bench_results_from_json",
    "compare_reachable_equilibrium_bench_results",
    "reachable_equilibrium_amplitude_calibration_report",
    "reachable_equilibrium_empirical_profile_from_amplitude",
    "export_calibration_bench_notebook_json",
    "export_calibration_bench_notebook_csv",
    "export_calibration_bench_packet_json",
    "export_contact_parameter_calibration_packet_json",
    "export_contact_parameter_calibration_packet_csv",
    "export_contact_parameter_calibration_results_template_json",
    "export_contact_parameter_bench_validation_json",
    "export_contact_parameter_bench_validation_csv",
    "export_contact_parameter_interval_calibration_json",
    "export_contact_parameter_interval_calibration_csv",
    "export_calibration_bench_execution_validation_json",
    "export_calibration_bench_execution_validation_csv",
    "export_physical_validation_readiness_json",
    "export_physical_validation_readiness_csv",
    "export_contact_state_abstraction_json",
    "export_contact_state_abstraction_csv",
    "export_contact_graph_consistency_json",
    "export_contact_graph_consistency_csv",
    "export_physical_realization_map_json",
    "export_physical_realization_map_csv",
    "export_equilibrium_relation_json",
    "export_equilibrium_relation_csv",
    "export_reachable_equilibrium_controllability_json",
    "export_reachable_equilibrium_controllability_csv",
    "export_reachable_equilibrium_bench_protocol_json",
    "export_reachable_equilibrium_bench_protocol_csv",
    "export_reachable_equilibrium_bench_results_template_json",
    "export_reachable_equilibrium_bench_comparison_json",
    "export_reachable_equilibrium_bench_comparison_csv",
    "export_reachable_equilibrium_amplitude_calibration_json",
    "export_reachable_equilibrium_amplitude_calibration_csv",
    "export_reachable_equilibrium_empirical_profile_json",
    "export_reachable_equilibrium_empirical_profile_csv",
    "export_calibration_model_profile_json",
    "export_calibration_model_profile_holdout_validation_json",
    "export_calibration_model_profile_holdout_validation_csv",
    "export_calibration_model_profile_residual_comparison_json",
    "export_calibration_model_profile_selection_json",
    "export_calibration_experiment_protocol_json",
    "export_calibration_experiment_results_template_json",
    "export_calibration_experiment_comparison_json",
    "export_calibration_experiment_comparison_report_json",
    "export_response_atlas_json",
    "export_response_atlas_sweep_json",
    "export_response_matrix_json",
    "export_removed_topology_reachability_comparison_json",
    "export_topology_experiment_report_json",
    "run_calibration_experiment_protocol",
    "solve_inverse_design",
    "inverse_design_report",
    "export_inverse_design_report_json",
    "validate_inverse_design_physical",
    "alpha_to_theta",
    "theta_to_alpha",
    "backlash_activation",
    "normalized_backlash_to_theta_dead_zone",
    "normalized_backlash_to_alpha_dead_zone",
    "characterize_response",
    "characterize_single_cell",
    "characterize_pair",
    "characterize_pairwise_interactions",
    "characterize_cluster",
    "compare_physical_response",
    "compare_physical_pair",
    "compare_physical_cluster",
    "response_decay_profile",
    "diagnose_programmable_discontinuity",
    "programmable_discontinuity_report",
    "formalization_target_manifest",
    "export_formalization_target_manifest_json",
    "export_programmable_discontinuity_report_json",
    "parse_lock_filename",
    "realized_lock_cells",
    "load_lock_dataset",
    "lock_dataset_summary",
    "export_lock_dataset_summary_json",
    "lock_record_cell_coordinates",
    "lock_coordinate_training_arrays",
    "lock_coordinate_dataset",
    "export_lock_coordinate_dataset_json",
    "lock_mask",
    "lock_angle_vector",
    "lock_feature_vector",
    "predict_lock_strand_shape",
    "calibrate_single_strand_from_lock_dataset",
    "calibrate_repeated_row_locks_from_lock_dataset",
    "train_lock_coordinate_mlp",
    "predict_lock_coordinate_mlp",
    "export_lock_coordinate_mlp_json",
    "alpha_backlash_operator",
    "vertical_clearance_operator",
    "finite_die_off_radius",
    "default_vertical_load_physical_scenarios",
    "build_vertical_load_physical_preview_report",
    "vertical_load_bench_packet",
    "export_vertical_load_bench_packet_json",
    "write_vertical_load_bench_packet_artifacts",
    "write_calibration_bench_packet_artifacts",
    "write_calibration_bench_execution_validation_artifacts",
    "write_browser_lock_dataset_artifact",
    "write_two_cell_bench_packet_artifacts",
    "write_two_cell_measurement_comparison_artifacts",
    "write_two_cell_external_comparison_artifacts",
    "write_vertical_load_energy_comparison_artifacts",
    "vertical_removal_physical_comparison_to_dict",
    "export_vertical_removal_physical_comparison_json",
    "export_vertical_load_physical_preview_report_json",
    "export_vertical_load_physical_preview_report_csv",
    "mechanics_energy_certificate_to_dict",
    "validate_vertical_load_energy_measurements",
    "vertical_load_energy_measurement_template",
    "vertical_load_energy_measurement_results_from_json",
    "compare_vertical_load_energy_measurement_results",
    "export_vertical_load_energy_measurement_template_json",
    "export_vertical_load_energy_validation_json",
    "export_vertical_load_energy_comparison_report_json",
    "vertical_load_energy_experiment_protocol",
    "export_vertical_load_energy_experiment_protocol_json",
    "local_actuation_event",
    "group_actuation_event",
    "lattice_topology_diagnostic",
    "lock_event",
    "release_event",
    "clear_actuation_event",
    "remove_cell_event",
    "restore_cell_event",
    "apply_programmable_event",
    "apply_event_sequence",
    "compare_event_order",
    "compare_group_actuation_decomposition",
    "compare_group_actuation_under_removal",
    "compare_vertical_residual_spring_hinge_3d",
    "compare_vertical_residual_under_removal",
    "compare_sequence_order",
    "lock_projection",
    "evaluate_programmable_operators",
    "model_provenance",
    "provenance_by_status",
    "provenance_summary",
    "physical_unit_scale_metadata",
    "export_physical_unit_scale_metadata_json",
    "simulate_kinematic",
    "solve_constraint_kinematic",
    "ConstraintKinematicSettings",
    "pair_distance_from_theta",
    "active_neighbor_edges",
    "solve_spring_hinge",
    "solve_spring_hinge_3d",
    "plot_lattice",
    "interactive_app",
]
