"""RAD backlash lattice simulator."""

from .cell_geometry import (
    PAPER_RAD_REFERENCE,
    PaperRADCalibration,
    PaperRADCellGeometry,
    PaperRADCellRecord,
    PaperRADConnectorGeometry,
    PaperRADLatticeGeometry,
    PaperRADReference,
    RADJointGeometry,
    build_paper_rad_cell_geometry,
    build_paper_rad_lattice_geometry,
    calibrate_paper_rad_config,
)
from .coupling import alpha_to_theta, backlash_activation, theta_to_alpha
from .experiments import (
    OperatorInteractionGraph,
    OperatorPairInteraction,
    PairCharacterization,
    PhysicalPairComparison,
    PhysicalResponseComparison,
    ResponseCharacterization,
    ResponseDecayProfile,
    ResponseMatrix,
    SourceCommand,
    build_response_matrix,
    characterize_cluster,
    characterize_pair,
    characterize_pairwise_interactions,
    characterize_response,
    characterize_single_cell,
    compare_physical_cluster,
    compare_physical_pair,
    compare_physical_response,
    response_decay_profile,
)
from .framework import (
    ProgrammableDiscontinuityDiagnostic,
    diagnose_programmable_discontinuity,
)
from .kinematic import simulate_kinematic
from .inverse import (
    InverseDesignResult,
    InversePhysicalValidation,
    solve_inverse_design,
    validate_inverse_design_physical,
)
from .mesh_export import (
    MeshComponent,
    PaperRADMesh,
    build_paper_rad_lattice_mesh,
    export_paper_rad_mesh_obj,
    iter_obj_vertices,
)
from .models import LatticeConfig, LatticeState, LoadCase, SimulationResult
from .operators import (
    DeadZonePropagationOperator,
    AdjacentSwapDiagnostic,
    EventCommutativityDiagnostic,
    PropagationResult,
    ProgrammableDiscontinuityEvent,
    SequenceOrderDiagnostic,
    StateDistanceDiagnostic,
    alpha_backlash_operator,
    apply_event_sequence,
    apply_programmable_event,
    clear_actuation_event,
    compare_event_order,
    compare_sequence_order,
    evaluate_programmable_operators,
    finite_die_off_radius,
    local_actuation_event,
    lock_event,
    lock_projection,
    release_event,
    vertical_clearance_operator,
)
from .spring_hinge import solve_spring_hinge, solve_spring_hinge_3d
from .visualization import interactive_app, plot_lattice

__all__ = [
    "LatticeConfig",
    "LatticeState",
    "LoadCase",
    "SimulationResult",
    "PaperRADReference",
    "PaperRADCalibration",
    "RADJointGeometry",
    "PaperRADCellGeometry",
    "PaperRADCellRecord",
    "PaperRADConnectorGeometry",
    "PaperRADLatticeGeometry",
    "MeshComponent",
    "PaperRADMesh",
    "PAPER_RAD_REFERENCE",
    "PropagationResult",
    "DeadZonePropagationOperator",
    "ProgrammableDiscontinuityEvent",
    "EventCommutativityDiagnostic",
    "StateDistanceDiagnostic",
    "AdjacentSwapDiagnostic",
    "SequenceOrderDiagnostic",
    "SourceCommand",
    "OperatorPairInteraction",
    "OperatorInteractionGraph",
    "ResponseCharacterization",
    "ResponseDecayProfile",
    "PairCharacterization",
    "PhysicalResponseComparison",
    "PhysicalPairComparison",
    "ResponseMatrix",
    "ProgrammableDiscontinuityDiagnostic",
    "InverseDesignResult",
    "InversePhysicalValidation",
    "build_paper_rad_cell_geometry",
    "build_paper_rad_lattice_geometry",
    "calibrate_paper_rad_config",
    "build_paper_rad_lattice_mesh",
    "export_paper_rad_mesh_obj",
    "iter_obj_vertices",
    "build_response_matrix",
    "solve_inverse_design",
    "validate_inverse_design_physical",
    "alpha_to_theta",
    "theta_to_alpha",
    "backlash_activation",
    "characterize_response",
    "characterize_single_cell",
    "characterize_pair",
    "characterize_pairwise_interactions",
    "characterize_cluster",
    "compare_physical_response",
    "compare_physical_pair",
    "compare_physical_cluster",
    "response_decay_profile",
    "diagnose_programmable_discontinuity",
    "alpha_backlash_operator",
    "vertical_clearance_operator",
    "finite_die_off_radius",
    "local_actuation_event",
    "lock_event",
    "release_event",
    "clear_actuation_event",
    "apply_programmable_event",
    "apply_event_sequence",
    "compare_event_order",
    "compare_sequence_order",
    "lock_projection",
    "evaluate_programmable_operators",
    "simulate_kinematic",
    "solve_spring_hinge",
    "solve_spring_hinge_3d",
    "plot_lattice",
    "interactive_app",
]
